/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.pcar.view;

import br.com.pcar.ctr.ClienteCTR;
import br.com.pcar.ctr.VendaCTR;
import br.com.pcar.dto.PcarDTO;
import br.com.pcar.dto.UsuarioDTO;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale; // Para formatação de moeda

public class CompraVIEW extends javax.swing.JDialog {

    private UsuarioDTO clienteLogadoDTO;
    private PcarDTO veiculoParaComprarDTO;
    private VendaCTR vendaCTR = new VendaCTR();
    private ClienteCTR clienteCTR = new ClienteCTR(); // Para buscar ID do cliente por CPF
    private boolean compraRealizada = false; // Flag para CatalogoClienteVIEW saber se deve atualizar

    /**
     * Creates new form CompraVIEW
     * @param parent O frame pai (CatalogoClienteVIEW)
     * @param modal Se o diálogo é modal
     * @param clienteLogado O DTO do cliente que está logado
     * @param veiculoSelecionado O DTO do veículo selecionado para compra
     */
    public CompraVIEW(java.awt.Frame parent, boolean modal, UsuarioDTO clienteLogado, PcarDTO veiculoSelecionado) {
        super(parent, modal);
        this.clienteLogadoDTO = clienteLogado;
        this.veiculoParaComprarDTO = veiculoSelecionado;
        
        initComponents(); // VOCÊ CRIARÁ ESTA UI NO NETBEANS
        
        this.setTitle("Confirmar Compra");
        setLocationRelativeTo(parent); // Centraliza em relação ao frame pai
        
        preencherDetalhesCompra();
    }

    private void preencherDetalhesCompra() {
        if (clienteLogadoDTO != null && veiculoParaComprarDTO != null) {
            lblNomeClienteCompra.setText(clienteLogadoDTO.getNome_usuario());
            lblVeiculoMarcaModelo.setText(veiculoParaComprarDTO.getMarca_veiculo() + " " + veiculoParaComprarDTO.getModelo_veiculo());
            lblVeiculoAno.setText(String.valueOf(veiculoParaComprarDTO.getAno_modelo_veiculo()));
            lblVeiculoCor.setText(veiculoParaComprarDTO.getCor_veiculo());
            lblVeiculoPlaca.setText(veiculoParaComprarDTO.getPlaca_veiculo());
            
            // Formatar preço para moeda local
            String precoFormatado = String.format(new Locale("pt", "BR"), "R$ %,.2f", veiculoParaComprarDTO.getPreco_veiculo());
            lblValorCompra.setText(precoFormatado);
            
            // Data atual para a venda
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy"); // Formato de exibição
            lblDataCompra.setText(sdf.format(new Date()));
        } else {
            JOptionPane.showMessageDialog(this, "Erro: Dados do cliente ou do veículo não foram recebidos corretamente.", "Erro de Inicialização", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }
    
    public boolean isCompraRealizada() {
        return compraRealizada;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloConfirmacao = new javax.swing.JLabel();
        pnlDetalhesCliente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblInfoCliente = new javax.swing.JLabel();
        lblNomeClienteCompra = new javax.swing.JLabel();
        pnlDetalhesVeiculo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblInfoVeiculo = new javax.swing.JLabel();
        lblVeiculoMarcaModelo = new javax.swing.JLabel();
        lblVeiculoAno1 = new javax.swing.JLabel();
        lblVeiculoAno = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblVeiculoPlaca = new javax.swing.JLabel();
        lblInfoValor = new javax.swing.JLabel();
        lblValorCompra = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblVeiculoCor = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblInfoData = new javax.swing.JLabel();
        lblDataCompra = new javax.swing.JLabel();
        pnlConfirmacao = new javax.swing.JPanel();
        btnConfirmarCompra = new javax.swing.JButton();
        btnCancelarCompra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Confirmar Compra");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblTituloConfirmacao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloConfirmacao.setText("Confirmação de Compra");

        pnlDetalhesCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.black, null, null));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Seus Dados");

        lblInfoCliente.setText("Cliente:");

        lblNomeClienteCompra.setText("[Nome do Cliente]");

        javax.swing.GroupLayout pnlDetalhesClienteLayout = new javax.swing.GroupLayout(pnlDetalhesCliente);
        pnlDetalhesCliente.setLayout(pnlDetalhesClienteLayout);
        pnlDetalhesClienteLayout.setHorizontalGroup(
            pnlDetalhesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalhesClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetalhesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetalhesClienteLayout.createSequentialGroup()
                        .addComponent(lblInfoCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNomeClienteCompra)
                        .addGap(0, 168, Short.MAX_VALUE))
                    .addGroup(pnlDetalhesClienteLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlDetalhesClienteLayout.setVerticalGroup(
            pnlDetalhesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalhesClienteLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetalhesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfoCliente)
                    .addComponent(lblNomeClienteCompra))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pnlDetalhesVeiculo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.black, null, null));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Veículo Selecionado");

        lblInfoVeiculo.setText("Veículo:");

        lblVeiculoMarcaModelo.setText("[Marca Modelo]");

        lblVeiculoAno1.setText("Ano:");

        lblVeiculoAno.setText("[Ano]");

        jLabel3.setText("Placa:");

        lblVeiculoPlaca.setText("[Placa]");

        lblInfoValor.setText("Valor Total:");

        lblValorCompra.setBackground(new java.awt.Color(0, 0, 0));
        lblValorCompra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValorCompra.setForeground(new java.awt.Color(0, 204, 0));
        lblValorCompra.setText("R$ [Valor]");

        jLabel5.setText("Cor:");

        lblVeiculoCor.setText("[Veiculo Cor]");

        javax.swing.GroupLayout pnlDetalhesVeiculoLayout = new javax.swing.GroupLayout(pnlDetalhesVeiculo);
        pnlDetalhesVeiculo.setLayout(pnlDetalhesVeiculoLayout);
        pnlDetalhesVeiculoLayout.setHorizontalGroup(
            pnlDetalhesVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalhesVeiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetalhesVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetalhesVeiculoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVeiculoCor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlDetalhesVeiculoLayout.createSequentialGroup()
                        .addGroup(pnlDetalhesVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(pnlDetalhesVeiculoLayout.createSequentialGroup()
                                .addComponent(lblInfoVeiculo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblVeiculoMarcaModelo))
                            .addGroup(pnlDetalhesVeiculoLayout.createSequentialGroup()
                                .addComponent(lblVeiculoAno1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblVeiculoAno, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlDetalhesVeiculoLayout.createSequentialGroup()
                        .addGroup(pnlDetalhesVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDetalhesVeiculoLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblVeiculoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDetalhesVeiculoLayout.createSequentialGroup()
                                .addComponent(lblInfoValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValorCompra)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlDetalhesVeiculoLayout.setVerticalGroup(
            pnlDetalhesVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalhesVeiculoLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetalhesVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfoVeiculo)
                    .addComponent(lblVeiculoMarcaModelo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetalhesVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVeiculoAno1)
                    .addComponent(lblVeiculoAno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetalhesVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblVeiculoCor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDetalhesVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblVeiculoPlaca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetalhesVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfoValor)
                    .addComponent(lblValorCompra))
                .addGap(31, 31, 31))
        );

        lblInfoData.setText("Data da Compra:");

        lblDataCompra.setText("[Data Inicial]");

        btnConfirmarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pcar/view/imagens/comprar.png"))); // NOI18N
        btnConfirmarCompra.setText("Confirmar Compra");
        btnConfirmarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarCompraActionPerformed(evt);
            }
        });

        btnCancelarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pcar/view/imagens/cancelar_1.png"))); // NOI18N
        btnCancelarCompra.setText("Cancelar Compra");
        btnCancelarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConfirmacaoLayout = new javax.swing.GroupLayout(pnlConfirmacao);
        pnlConfirmacao.setLayout(pnlConfirmacaoLayout);
        pnlConfirmacaoLayout.setHorizontalGroup(
            pnlConfirmacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfirmacaoLayout.createSequentialGroup()
                .addComponent(btnConfirmarCompra)
                .addGap(38, 38, 38)
                .addComponent(btnCancelarCompra)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlConfirmacaoLayout.setVerticalGroup(
            pnlConfirmacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfirmacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnConfirmarCompra)
                .addComponent(btnCancelarCompra))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfoData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlConfirmacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlConfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblInfoData)
                        .addComponent(lblDataCompra)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(lblTituloConfirmacao))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pnlDetalhesCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlDetalhesVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloConfirmacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDetalhesCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDetalhesVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarCompraActionPerformed
        if (clienteLogadoDTO == null || veiculoParaComprarDTO == null) {
            JOptionPane.showMessageDialog(this, "Erro: Dados do cliente ou veículo não disponíveis.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 1. Obter o ID do cliente da tabela 'clientes' usando o CPF do UsuarioDTO
        String cpfCliente = clienteLogadoDTO.getCpf_usuario();
System.out.println("DEBUG CompraVIEW: CPF sendo usado para busca: '" + cpfCliente + "'"); 
        if (cpfCliente == null || cpfCliente.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Erro: CPF do cliente não encontrado para registrar a venda.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int idClienteTabela = clienteCTR.buscarIdClientePorCPF(cpfCliente); // Usa o novo método
        
        if (idClienteTabela == -1) {
            JOptionPane.showMessageDialog(this, "Erro: Cliente não encontrado no cadastro de clientes com o CPF: " + cpfCliente, "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        PcarDTO novaVendaDTO = new PcarDTO(); //
        novaVendaDTO.setId_cliente(idClienteTabela); // ID da tabela clientes
        novaVendaDTO.setId_veiculo(veiculoParaComprarDTO.getId_veiculo()); //
        
        // Data da Venda no formato YYYY-MM-DD
        SimpleDateFormat sdfDb = new SimpleDateFormat("yyyy-MM-dd");
        novaVendaDTO.setData_venda(sdfDb.format(new Date())); //
        
        novaVendaDTO.setValor_venda(veiculoParaComprarDTO.getPreco_veiculo()); //
        novaVendaDTO.setStatus_venda("Pendente"); // Status inicial

        String resultado = vendaCTR.inserirVenda(novaVendaDTO); //
        JOptionPane.showMessageDialog(this, resultado, "Status da Compra", JOptionPane.INFORMATION_MESSAGE);

        if (resultado.toLowerCase().contains("sucesso")) {
            this.compraRealizada = true;
            // Opcional: Marcar o veículo como "Vendido" ou "Reservado" no banco de dados
            // Isso exigiria um método em VeiculoCTR/DAO para atualizar o status do veículo.
            // Ex: veiculoCTR.atualizarStatusVeiculo(veiculoParaComprarDTO.getId_veiculo(), "Vendido");
            this.dispose(); // Fecha o diálogo de compra
        }
    }//GEN-LAST:event_btnConfirmarCompraActionPerformed

    private void btnCancelarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCompraActionPerformed
       this.compraRealizada = false;
        this.dispose(); // Simplesmente fecha o diálogo
    }//GEN-LAST:event_btnCancelarCompraActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarCompra;
    private javax.swing.JButton btnConfirmarCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblDataCompra;
    private javax.swing.JLabel lblInfoCliente;
    private javax.swing.JLabel lblInfoData;
    private javax.swing.JLabel lblInfoValor;
    private javax.swing.JLabel lblInfoVeiculo;
    private javax.swing.JLabel lblNomeClienteCompra;
    private javax.swing.JLabel lblTituloConfirmacao;
    private javax.swing.JLabel lblValorCompra;
    private javax.swing.JLabel lblVeiculoAno;
    private javax.swing.JLabel lblVeiculoAno1;
    private javax.swing.JLabel lblVeiculoCor;
    private javax.swing.JLabel lblVeiculoMarcaModelo;
    private javax.swing.JLabel lblVeiculoPlaca;
    private javax.swing.JPanel pnlConfirmacao;
    private javax.swing.JPanel pnlDetalhesCliente;
    private javax.swing.JPanel pnlDetalhesVeiculo;
    // End of variables declaration//GEN-END:variables
}
